language: node_js
node_js:
- '7'
before_deploy:
- webpack
deploy:
  provider: npm
  email: snroca@hotmail.com
  api_key:
    secure: Q4Semd+vQx1MfdoaD2+cNwKhy+dxKoNLL6gzvwujlibkX5nlyDVeMzOYqi6rSbAowY2CBgnBEDUWgIqrKtArpSOAIm4bFSKm40YXPN9r7lOPf0NdpXhqNhdXuSBTLIe/h4H9amu3DdnI3pqYNhbKYxshc9UVY99S3xm73expcV+GRTQZNuj+z5wriUkxQatRH/bD1qFQ3aUilbhi/HS8RHm+UN7V3kPqS/V8lmWVJ52w2Z5uRDpKzfSf+MOV0z2gLM36tD09q6BjIY6OGS0BDCivhfBNtf0eL5WMPak+EN5Pu1USjOvq5PswkysBdNVYa1JYY7KgktV/902QBxVJPKWyzN1VFswAQNSVfsue5EPZ7JnTNMNX8nv/iFML72ZtBcHw4Rynur10DPGk7o4i3bLwOn7JWyOYBAbFrj3wI4RqtknxaB0RMAPzmiJsAszDyKHGwQ2vbAyoVSJqD83MKMOpw1IIACvRR3FSMtMj+CGwKoVRSJZpWvoKkT4hie0DjXh7ilMCCbQ5rKweD+/ueUu06+HFzIHwWWja18YEJlEQ8DYAUyd2LLEwfuIBai9918uPyIXMW0KjRMTHnXO+iuNZ3i3bmXa1FfEaoya4+HA7tke2Y+oITqqQ5KE4QZwu3NdIdCYeoB5ZZobDScRyLQZTcVqDSIPeywY02/KHdI0=
  on:
    repo: santiiiii/fast-image-viewer
branches:
  only:
  - master
